export default [
    {
        "id": 1,
        "title": "cup",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/ikea-kruzka-belyj__0328951_PE520152_S4.JPG",
        "price": "130 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 2,
        "title": "pillow",
        "imageUrl": "https://www.ikea.com\/ru\/ru\/images\/products\/ursula-cehol-na-podusku__0503667_PE632848_S4.JPG",
        "price": "600 руб.",
        "width": "300px",
        "height": "300px",
    },

    {
        "id": 3,
        "title": "box",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/pingla-korobka-s-kryskoj-cernyj__0398498_PE563788_S4.JPG",
        "price": "100 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 4,
        "title": "plate",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/vardagen-tarelka-seryj__0445947_PE596164_S4.JPG",
        "price": "100 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 5,
        "title": "frame",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/virserum-rama-zeltyj__0202741_PE359077_S4.JPG",
        "price": "150 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 6,
        "title": "plaid",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/lizamari-pled-sinij__0491584_PE625239_S4.JPG",
        "price": "400 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 7,
        "title": "curtains",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/mariatistel-gardiny-para-zeltyj__0399387_PE564432_S4.JPG",
        "price": "2000 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 8,
        "title": "chair",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/sven-bertil-stul-cernyj__0483195_PE620715_S4.JPG",
        "price": "2900 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 9,
        "title": "sofa",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/klippan-divan-mestnyj-raznye-cveta__0562992_PE663645_S4.JPG",
        "price": "13000 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 10,
        "title": "bed",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/nordli-karkas-krovati-s-asikami-belyj__0494839_PE627362_S4.JPG",
        "price": "22000 руб.",
        "width": "300px",
        "height": "300px",
    },
    {
        "id": 11,
        "title": "mirror",
        "imageUrl": "https:\/\/www.ikea.com\/ru\/ru\/images\/products\/frekk-zerkalo__26262_PE092247_S4.JPG",
        "price": "500 руб.",
        "width": "300px",
        "height": "300px",
    }
]